name: Post Year Progress

on:
  schedule:
    # Runs daily at 00:00 (Midnight) Tashkent Time (GMT+5) / 19:00 UTC
    - cron: '0 19 * * *'
  workflow_dispatch: # Allows manual triggers from Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python main.py
